#!/bin/sh
# bspwm config

# initialize desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# make borders black
bspc config normal_border_color "#262425"
bspc config active_border_color "#262425"
bspc config focused_border_color "#262425"
bspc config presel_feedback_color "#262425"

# make borders bigger
bspc config border_width 32

# make a window gap
bspc config window_gap 96
